# Generated by Django 3.1.1 on 2020-09-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='current_viewers',
        ),
    ]
