# Generated by Django 3.1.1 on 2020-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_story_current_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='current_viewers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
