# Generated by Django 3.1.1 on 2020-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_story_current_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='isCurrentlyReading',
            field=models.BooleanField(default=False),
        ),
    ]
